language: node_js
cache: yarn
script:
- echo "skipping tests"
before_deploy: yarn build
deploy:
  - provider: pages
    local-dir: dist
    github-token: $GITHUB_TOKEN
    skip-cleanup: true
    keep-history: true
    on:
      branch: master
